// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCEPG.Infrastructure.DataAccess.Base;

#nullable disable

namespace OCEPG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Atendimento", b =>
                {
                    b.Property<int>("Protocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Protocolo"));

                    b.Property<string>("Comentario")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAssunto")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<byte?>("Prioridade")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("StatusAtend")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Protocolo");

                    b.HasIndex(new[] { "IdAssunto" }, "IX_Atendimento_IdAssunto");

                    b.HasIndex(new[] { "IdCliente" }, "IX_Atendimento_IdCliente");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Atendimento_UsuarioId");

                    b.ToTable("Atendimento", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataInscricao")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Foto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short?>("Idade")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Mensalidade")
                        .HasColumnType("smallmoney");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Texto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TipoId" }, "IX_Cliente_TipoId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Resolucao", b =>
                {
                    b.Property<int>("Protocolo")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Protocolo");

                    b.ToTable("Resolucao", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("TipoCliente", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<short>("Funcao")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("UNIQUEIDENTIFIER ROWGUIDCOL");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserIdentifier");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.UsuarioRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("UsuarioRole", (string)null);
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Atendimento", b =>
                {
                    b.HasOne("OCPEG.Domain.DataAccess.Entities.Assunto", "IdAssuntoNavigation")
                        .WithMany("Atendimentos")
                        .HasForeignKey("IdAssunto")
                        .HasConstraintName("FK_Atendimento_Assunto");

                    b.HasOne("OCPEG.Domain.DataAccess.Entities.Cliente", "IdClienteNavigation")
                        .WithMany("Atendimentos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_Atendimento_Cliente");

                    b.HasOne("OCPEG.Domain.DataAccess.Entities.Usuario", null)
                        .WithMany("Atendimentos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("IdAssuntoNavigation");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Cliente", b =>
                {
                    b.HasOne("OCPEG.Domain.DataAccess.Entities.TipoCliente", "Tipo")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoId")
                        .HasConstraintName("FK_Cliente_Tipo");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Resolucao", b =>
                {
                    b.HasOne("OCPEG.Domain.DataAccess.Entities.Atendimento", "ProtocoloNavigation")
                        .WithOne("Resolucao")
                        .HasForeignKey("OCPEG.Domain.DataAccess.Entities.Resolucao", "Protocolo")
                        .IsRequired()
                        .HasConstraintName("FK_Resolucao_Resolucao");

                    b.Navigation("ProtocoloNavigation");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Assunto", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Atendimento", b =>
                {
                    b.Navigation("Resolucao");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Cliente", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("OCPEG.Domain.DataAccess.Entities.Usuario", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
